env: local
grpc:
  port: 50051
db:
  host: "localhost"
  port: 54320
  db_name: "auth"
  password: "POSTGRES_PASSWORD"
  user: "POSTGRES_USER"
redis:
  host: "localhost"
  port: "63790"
kafka:
  brokers:
    - "localhost:9092"
    - "localhost:9093"
    - "localhost:9094"
  group:
    "test"
  topicName:
    "myTestTopic"